# Generated by Django 6.1 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
