# Generated by Django 6.1 on 2026-09-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_tenderdocument_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('eligibility', 'Eligibility'), ('legal', 'Legal'), ('other', 'Other')], default='other', max_length=50)),
                ('requirement_text', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='documents.tenderdocument')),
            ],
        ),
    ]
