# Generated by Django 6.1 on 2026-09-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_projectsolution'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], max_length=30)),
                ('confidence_score', models.FloatField(default=0)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='projects.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='documents.requirement')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='documents.projectsolution')),
            ],
        ),
    ]
