# Generated by Django 6.1 on 2026-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_complianceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceresult',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complianceresult',
            name='status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], default='non_compliant', max_length=30),
        ),
    ]
