# Generated by Django 6.1 on 2026-09-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_complianceresult_explanation_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20)),
                ('risk_score', models.FloatField(default=0)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='projects.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='documents.requirement')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='documents.projectsolution')),
            ],
        ),
    ]
