# Generated by Django 6.1 on 2026-09-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_riskanalysis'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='projects.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='documents.requirement')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='documents.projectsolution')),
            ],
        ),
    ]
